
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/spring_filters_course_db?useSSL=false&serverTimezone=UTC
      username: docker
      password: docker
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

